-- OMSWD Pandan complete Supabase setup
-- Paste this whole file into the Supabase SQL Editor and run it once.

create extension if not exists pgcrypto;

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = timezone('utc', now());
  return new;
end;
$$;

create table if not exists public.roles (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  description text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text unique,
  full_name text,
  avatar_url text,
  phone_number text,
  role text check (role in ('resident', 'admin', 'super_admin', 'social_worker')),
  barangay text,
  municipality text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  role_id bigint not null references public.roles(id) on delete cascade,
  assigned_by uuid references auth.users(id) on delete set null,
  assigned_at timestamptz not null default timezone('utc', now()),
  unique (user_id, role_id)
);

create table if not exists public.municipalities (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  province text not null,
  region text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (name, province)
);

create table if not exists public.barangays (
  id uuid primary key default gen_random_uuid(),
  municipality_id uuid not null references public.municipalities(id) on delete cascade,
  name text not null,
  code text,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (municipality_id, name)
);

create table if not exists public.residents (
  id uuid primary key default gen_random_uuid(),
  profile_id uuid not null unique references public.profiles(id) on delete cascade,
  resident_code text unique,
  first_name text not null,
  middle_name text,
  last_name text not null,
  suffix text,
  birth_date date,
  sex text,
  civil_status text,
  contact_number text,
  address_line text,
  barangay_id uuid references public.barangays(id) on delete set null,
  municipality_id uuid references public.municipalities(id) on delete set null,
  government_id_type text,
  government_id_number text,
  household_size integer,
  monthly_income numeric(12,2),
  is_verified boolean not null default false,
  verified_at timestamptz,
  verified_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.assistance_types (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  category text,
  description text,
  estimated_processing_days integer,
  is_active boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.assistance_requirements (
  id uuid primary key default gen_random_uuid(),
  assistance_type_id uuid not null references public.assistance_types(id) on delete cascade,
  name text not null,
  description text,
  document_type text,
  is_required boolean not null default true,
  sort_order integer not null default 0,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.applications (
  id uuid primary key default gen_random_uuid(),
  reference_number text not null unique,
  applicant_profile_id uuid references public.profiles(id) on delete set null,
  resident_id uuid references public.residents(id) on delete set null,
  assistance_type_id uuid not null references public.assistance_types(id) on delete restrict,
  status text not null default 'pending_verification' check (
    status in (
      'draft',
      'pending_verification',
      'under_review',
      'for_requirements',
      'for_correction',
      'approved',
      'rejected',
      'completed'
    )
  ),
  urgency text,
  requested_amount numeric(12,2),
  request_reason text not null,
  applicant_full_name text not null,
  applicant_email text not null,
  contact_number text not null,
  birth_date date,
  sex text,
  civil_status text,
  address_line text not null,
  applicant_barangay text,
  applicant_municipality text,
  barangay_id uuid references public.barangays(id) on delete set null,
  municipality_id uuid references public.municipalities(id) on delete set null,
  household_size integer,
  monthly_income numeric(12,2),
  government_id_type text,
  government_id_number text,
  consent_accepted boolean not null default false,
  submitted_at timestamptz not null default timezone('utc', now()),
  reviewed_at timestamptz,
  assigned_to uuid references auth.users(id) on delete set null,
  admin_remarks text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.application_requirements (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  requirement_id uuid not null references public.assistance_requirements(id) on delete cascade,
  status text not null default 'pending' check (
    status in ('pending', 'submitted', 'approved', 'rejected', 'needs_resubmission')
  ),
  remarks text,
  reviewed_by uuid references auth.users(id) on delete set null,
  reviewed_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (application_id, requirement_id)
);

create table if not exists public.uploaded_documents (
  id uuid primary key default gen_random_uuid(),
  application_id uuid references public.applications(id) on delete cascade,
  application_requirement_id uuid references public.application_requirements(id) on delete cascade,
  resident_id uuid references public.residents(id) on delete cascade,
  bucket text not null,
  file_path text not null unique,
  file_name text not null,
  mime_type text,
  size_bytes bigint,
  status text not null default 'uploaded' check (
    status in ('uploaded', 'approved', 'rejected', 'archived')
  ),
  remarks text,
  uploaded_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.verification_logs (
  id uuid primary key default gen_random_uuid(),
  application_id uuid references public.applications(id) on delete cascade,
  resident_id uuid references public.residents(id) on delete cascade,
  verified_by uuid not null references auth.users(id) on delete restrict,
  action text not null,
  remarks text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.status_histories (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  previous_status text,
  new_status text not null,
  changed_by uuid references auth.users(id) on delete set null,
  remarks text,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  recipient_id uuid not null references auth.users(id) on delete cascade,
  title text not null,
  message text not null,
  category text not null default 'system',
  link_url text,
  read_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.announcements (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  title text not null,
  summary text,
  content text not null,
  is_published boolean not null default false,
  published_at timestamptz,
  posted_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.faqs (
  id uuid primary key default gen_random_uuid(),
  category text not null default 'general',
  question text not null,
  answer text not null,
  sort_order integer not null default 0,
  is_published boolean not null default true,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.audit_logs (
  id uuid primary key default gen_random_uuid(),
  actor_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text not null,
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.email_logs (
  id uuid primary key default gen_random_uuid(),
  recipient_email text not null,
  subject text not null,
  template text not null,
  status text not null default 'queued' check (status in ('queued', 'sent', 'failed')),
  related_application_id uuid references public.applications(id) on delete set null,
  payload jsonb not null default '{}'::jsonb,
  sent_at timestamptz,
  created_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.staff_assignments (
  id uuid primary key default gen_random_uuid(),
  application_id uuid not null references public.applications(id) on delete cascade,
  staff_user_id uuid not null references auth.users(id) on delete cascade,
  assignment_role text not null,
  notes text,
  assigned_at timestamptz not null default timezone('utc', now()),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  unique (application_id, staff_user_id, assignment_role)
);

create table if not exists public.settings (
  id uuid primary key default gen_random_uuid(),
  setting_key text not null unique,
  setting_value jsonb not null default '{}'::jsonb,
  description text,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_profiles_role on public.profiles(role);
create index if not exists idx_user_roles_user_id on public.user_roles(user_id);
create index if not exists idx_barangays_municipality_id on public.barangays(municipality_id);
create index if not exists idx_residents_profile_id on public.residents(profile_id);
create index if not exists idx_residents_barangay_id on public.residents(barangay_id);
create index if not exists idx_applications_profile_id on public.applications(applicant_profile_id);
create index if not exists idx_applications_resident_id on public.applications(resident_id);
create index if not exists idx_applications_assistance_type_id on public.applications(assistance_type_id);
create index if not exists idx_applications_status on public.applications(status);
create index if not exists idx_applications_barangay_id on public.applications(barangay_id);
create index if not exists idx_app_requirements_application_id on public.application_requirements(application_id);
create index if not exists idx_uploaded_documents_application_id on public.uploaded_documents(application_id);
create index if not exists idx_notifications_recipient_id on public.notifications(recipient_id);
create index if not exists idx_status_histories_application_id on public.status_histories(application_id);
create index if not exists idx_staff_assignments_application_id on public.staff_assignments(application_id);

drop trigger if exists set_profiles_updated_at on public.profiles;
create trigger set_profiles_updated_at before update on public.profiles for each row execute function public.set_updated_at();
drop trigger if exists set_municipalities_updated_at on public.municipalities;
create trigger set_municipalities_updated_at before update on public.municipalities for each row execute function public.set_updated_at();
drop trigger if exists set_barangays_updated_at on public.barangays;
create trigger set_barangays_updated_at before update on public.barangays for each row execute function public.set_updated_at();
drop trigger if exists set_residents_updated_at on public.residents;
create trigger set_residents_updated_at before update on public.residents for each row execute function public.set_updated_at();
drop trigger if exists set_assistance_types_updated_at on public.assistance_types;
create trigger set_assistance_types_updated_at before update on public.assistance_types for each row execute function public.set_updated_at();
drop trigger if exists set_assistance_requirements_updated_at on public.assistance_requirements;
create trigger set_assistance_requirements_updated_at before update on public.assistance_requirements for each row execute function public.set_updated_at();
drop trigger if exists set_applications_updated_at on public.applications;
create trigger set_applications_updated_at before update on public.applications for each row execute function public.set_updated_at();
drop trigger if exists set_application_requirements_updated_at on public.application_requirements;
create trigger set_application_requirements_updated_at before update on public.application_requirements for each row execute function public.set_updated_at();
drop trigger if exists set_uploaded_documents_updated_at on public.uploaded_documents;
create trigger set_uploaded_documents_updated_at before update on public.uploaded_documents for each row execute function public.set_updated_at();
drop trigger if exists set_announcements_updated_at on public.announcements;
create trigger set_announcements_updated_at before update on public.announcements for each row execute function public.set_updated_at();
drop trigger if exists set_staff_assignments_updated_at on public.staff_assignments;
create trigger set_staff_assignments_updated_at before update on public.staff_assignments for each row execute function public.set_updated_at();
drop trigger if exists set_settings_updated_at on public.settings;
create trigger set_settings_updated_at before update on public.settings for each row execute function public.set_updated_at();

insert into public.roles (code, name, description)
values
  ('resident', 'Resident', 'Resident portal account'),
  ('admin', 'Administrator', 'Administrator with operational access'),
  ('super_admin', 'Super Administrator', 'Full platform control'),
  ('social_worker', 'Social Worker', 'Case review and resident verification')
on conflict (code) do update
set name = excluded.name, description = excluded.description;

insert into public.assistance_types (slug, name, category, description, estimated_processing_days, is_active)
values
  ('medical-assistance', 'Medical Assistance', 'Health', 'Support for medicines, laboratory work, or urgent treatment expenses.', 7, true),
  ('burial-assistance', 'Burial Assistance', 'Emergency', 'Immediate assistance for burial-related costs during bereavement.', 5, true),
  ('food-relief', 'Food Relief', 'Basic Needs', 'Short-term food support for vulnerable households in crisis.', 3, true),
  ('educational-assistance', 'Educational Assistance', 'Education', 'Limited support for school-related expenses and learning needs.', 10, true)
on conflict (slug) do update
set
  name = excluded.name,
  category = excluded.category,
  description = excluded.description,
  estimated_processing_days = excluded.estimated_processing_days,
  is_active = excluded.is_active;

create or replace function public.seed_application_requirements()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.application_requirements (application_id, requirement_id, status)
  select
    new.id,
    ar.id,
    'pending'
  from public.assistance_requirements ar
  where ar.assistance_type_id = new.assistance_type_id
  on conflict (application_id, requirement_id) do nothing;

  return new;
end;
$$;

drop trigger if exists seed_application_requirements_on_insert on public.applications;
create trigger seed_application_requirements_on_insert
after insert on public.applications
for each row
execute function public.seed_application_requirements();

insert into public.application_requirements (application_id, requirement_id, status)
select
  a.id,
  ar.id,
  'pending'
from public.applications a
join public.assistance_requirements ar on ar.assistance_type_id = a.assistance_type_id
left join public.application_requirements apr
  on apr.application_id = a.id
 and apr.requirement_id = ar.id
where apr.id is null;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  requested_role text;
  metadata jsonb;
  resident_first_name text;
  resident_middle_name text;
  resident_last_name text;
  resident_suffix text;
  resident_full_name text;
  resident_municipality text;
  resident_barangay text;
  municipality_record_id uuid;
  barangay_record_id uuid;
begin
  metadata := coalesce(new.raw_user_meta_data, '{}'::jsonb);
  requested_role := coalesce(metadata ->> 'role', 'resident');
  resident_full_name := nullif(metadata ->> 'full_name', '');
  resident_first_name := nullif(metadata ->> 'first_name', '');
  resident_middle_name := nullif(metadata ->> 'middle_name', '');
  resident_last_name := nullif(metadata ->> 'last_name', '');
  resident_suffix := nullif(metadata ->> 'suffix', '');
  resident_municipality := nullif(metadata ->> 'municipality', '');
  resident_barangay := nullif(metadata ->> 'barangay', '');

  if resident_first_name is null and resident_full_name is not null then
    resident_first_name := split_part(resident_full_name, ' ', 1);
  end if;

  if resident_last_name is null then
    resident_last_name := coalesce(resident_full_name, resident_first_name, 'Resident');
  end if;

  select m.id
  into municipality_record_id
  from public.municipalities m
  where lower(m.name) = lower(coalesce(resident_municipality, 'Pandan'))
  order by m.name
  limit 1;

  select b.id
  into barangay_record_id
  from public.barangays b
  where lower(b.name) = lower(coalesce(resident_barangay, ''))
    and (
      municipality_record_id is null
      or b.municipality_id = municipality_record_id
    )
  order by b.name
  limit 1;

  insert into public.profiles (id, email, full_name, phone_number, role, barangay, municipality, is_active)
  values (
    new.id,
    new.email,
    resident_full_name,
    metadata ->> 'phone_number',
    requested_role,
    resident_barangay,
    resident_municipality,
    coalesce((metadata ->> 'is_active')::boolean, true)
  )
  on conflict (id) do update
  set
    email = excluded.email,
    full_name = coalesce(excluded.full_name, public.profiles.full_name),
    phone_number = coalesce(excluded.phone_number, public.profiles.phone_number),
    role = coalesce(excluded.role, public.profiles.role),
    barangay = coalesce(excluded.barangay, public.profiles.barangay),
    municipality = coalesce(excluded.municipality, public.profiles.municipality),
    is_active = excluded.is_active;

  if requested_role = 'resident' then
    insert into public.residents (
      profile_id,
      resident_code,
      first_name,
      middle_name,
      last_name,
      suffix,
      birth_date,
      sex,
      civil_status,
      contact_number,
      address_line,
      barangay_id,
      municipality_id,
      government_id_type,
      government_id_number
    )
    values (
      new.id,
      'RES-' || upper(substr(replace(new.id::text, '-', ''), 1, 8)),
      coalesce(resident_first_name, 'Resident'),
      resident_middle_name,
      coalesce(resident_last_name, 'Resident'),
      resident_suffix,
      nullif(metadata ->> 'birth_date', '')::date,
      nullif(metadata ->> 'sex', ''),
      nullif(metadata ->> 'civil_status', ''),
      nullif(metadata ->> 'phone_number', ''),
      nullif(metadata ->> 'address_line', ''),
      barangay_record_id,
      municipality_record_id,
      nullif(metadata ->> 'government_id_type', ''),
      nullif(metadata ->> 'government_id_number', '')
    )
    on conflict (profile_id) do update
    set
      first_name = excluded.first_name,
      middle_name = excluded.middle_name,
      last_name = excluded.last_name,
      suffix = excluded.suffix,
      birth_date = excluded.birth_date,
      sex = excluded.sex,
      civil_status = excluded.civil_status,
      contact_number = excluded.contact_number,
      address_line = excluded.address_line,
      barangay_id = excluded.barangay_id,
      municipality_id = excluded.municipality_id,
      government_id_type = excluded.government_id_type,
      government_id_number = excluded.government_id_number;
  end if;

  insert into public.user_roles (user_id, role_id)
  select new.id, r.id
  from public.roles r
  where r.code = requested_role
  on conflict (user_id, role_id) do nothing;

  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();

create or replace function public.has_role(required_roles text[])
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    exists (
      select 1
      from public.user_roles ur
      join public.roles r on r.id = ur.role_id
      where ur.user_id = auth.uid()
        and r.code = any(required_roles)
    )
    or exists (
      select 1
      from public.profiles p
      where p.id = auth.uid()
        and p.role = any(required_roles)
    );
$$;

insert into storage.buckets (id, name, public)
values
  ('resident-documents', 'resident-documents', false),
  ('application-documents', 'application-documents', false),
  ('ids', 'ids', false),
  ('requirements', 'requirements', false)
on conflict (id) do update
set public = excluded.public;

alter table public.profiles enable row level security;
alter table public.residents enable row level security;
alter table public.assistance_types enable row level security;
alter table public.assistance_requirements enable row level security;
alter table public.applications enable row level security;
alter table public.application_requirements enable row level security;
alter table public.uploaded_documents enable row level security;
alter table public.verification_logs enable row level security;
alter table public.status_histories enable row level security;
alter table public.notifications enable row level security;
alter table public.announcements enable row level security;
alter table public.faqs enable row level security;
alter table public.barangays enable row level security;
alter table public.municipalities enable row level security;
alter table public.audit_logs enable row level security;
alter table public.email_logs enable row level security;
alter table public.staff_assignments enable row level security;
alter table public.settings enable row level security;
alter table public.roles enable row level security;
alter table public.user_roles enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin" on public.profiles for select using (
  auth.uid() = id or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "profiles_insert_own_or_admin" on public.profiles;
create policy "profiles_insert_own_or_admin" on public.profiles for insert with check (
  auth.uid() = id or public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "profiles_update_own_or_admin" on public.profiles;
create policy "profiles_update_own_or_admin" on public.profiles for update using (
  auth.uid() = id or public.has_role(array['admin', 'super_admin'])
) with check (
  auth.uid() = id or public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "roles_admin_only" on public.roles;
create policy "roles_admin_only" on public.roles for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "user_roles_admin_only" on public.user_roles;
create policy "user_roles_admin_only" on public.user_roles for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "locations_select_authenticated" on public.municipalities;
create policy "locations_select_authenticated" on public.municipalities for select using (
  auth.role() = 'authenticated'
);

drop policy if exists "barangays_select_authenticated" on public.barangays;
create policy "barangays_select_authenticated" on public.barangays for select using (
  auth.role() = 'authenticated'
);

drop policy if exists "locations_admin_manage" on public.municipalities;
create policy "locations_admin_manage" on public.municipalities for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "barangays_admin_manage" on public.barangays;
create policy "barangays_admin_manage" on public.barangays for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "residents_select_own_or_admin" on public.residents;
create policy "residents_select_own_or_admin" on public.residents for select using (
  profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "residents_insert_self_or_admin" on public.residents;
create policy "residents_insert_self_or_admin" on public.residents for insert with check (
  profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "residents_update_own_or_admin" on public.residents;
create policy "residents_update_own_or_admin" on public.residents for update using (
  profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "assistance_types_public_select" on public.assistance_types;
create policy "assistance_types_public_select" on public.assistance_types for select using (is_active = true);

drop policy if exists "assistance_types_admin_manage" on public.assistance_types;
create policy "assistance_types_admin_manage" on public.assistance_types for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "assistance_requirements_public_select" on public.assistance_requirements;
create policy "assistance_requirements_public_select" on public.assistance_requirements for select using (
  exists (
    select 1
    from public.assistance_types at
    where at.id = assistance_type_id
      and at.is_active = true
  )
);

drop policy if exists "assistance_requirements_admin_manage" on public.assistance_requirements;
create policy "assistance_requirements_admin_manage" on public.assistance_requirements for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "applications_select_own_or_admin" on public.applications;
create policy "applications_select_own_or_admin" on public.applications for select using (
  applicant_profile_id = auth.uid()
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "applications_insert_authenticated" on public.applications;
create policy "applications_insert_authenticated" on public.applications for insert with check (
  auth.uid() = applicant_profile_id and consent_accepted = true
);

drop policy if exists "applications_update_admin_or_owner_pending" on public.applications;
create policy "applications_update_admin_or_owner_pending" on public.applications for update using (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
  or (applicant_profile_id = auth.uid() and status in ('draft', 'pending_verification', 'for_correction'))
) with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
  or (applicant_profile_id = auth.uid() and status in ('draft', 'pending_verification', 'for_correction'))
);

drop policy if exists "application_requirements_select_own_or_admin" on public.application_requirements;
create policy "application_requirements_select_own_or_admin" on public.application_requirements for select using (
  exists (
    select 1
    from public.applications a
    where a.id = application_id
      and (a.applicant_profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker']))
  )
);

drop policy if exists "application_requirements_admin_manage" on public.application_requirements;
create policy "application_requirements_admin_manage" on public.application_requirements for all using (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "uploaded_documents_select_own_or_admin" on public.uploaded_documents;
create policy "uploaded_documents_select_own_or_admin" on public.uploaded_documents for select using (
  uploaded_by = auth.uid()
  or exists (
    select 1
    from public.applications a
    where a.id = application_id
      and (a.applicant_profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker']))
  )
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "uploaded_documents_insert_authenticated" on public.uploaded_documents;
create policy "uploaded_documents_insert_authenticated" on public.uploaded_documents for insert with check (
  uploaded_by = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "uploaded_documents_update_admin" on public.uploaded_documents;
create policy "uploaded_documents_update_admin" on public.uploaded_documents for update using (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "verification_logs_admin_only" on public.verification_logs;
create policy "verification_logs_admin_only" on public.verification_logs for all using (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "status_histories_select_own_or_admin" on public.status_histories;
create policy "status_histories_select_own_or_admin" on public.status_histories for select using (
  exists (
    select 1
    from public.applications a
    where a.id = application_id
      and (a.applicant_profile_id = auth.uid() or public.has_role(array['admin', 'super_admin', 'social_worker']))
  )
);

drop policy if exists "status_histories_insert_initial_or_admin" on public.status_histories;
create policy "status_histories_insert_initial_or_admin" on public.status_histories for insert with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
  or (
    changed_by = auth.uid()
    and previous_status is null
    and new_status = 'pending_verification'
    and exists (
      select 1
      from public.applications a
      where a.id = application_id
        and a.applicant_profile_id = auth.uid()
    )
  )
);

drop policy if exists "notifications_select_own" on public.notifications;
create policy "notifications_select_own" on public.notifications for select using (
  recipient_id = auth.uid() or public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "notifications_update_own" on public.notifications;
create policy "notifications_update_own" on public.notifications for update using (
  recipient_id = auth.uid()
) with check (
  recipient_id = auth.uid()
);

drop policy if exists "notifications_admin_insert" on public.notifications;
create policy "notifications_admin_insert" on public.notifications for insert with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "announcements_public_select" on public.announcements;
create policy "announcements_public_select" on public.announcements for select using (is_published = true);

drop policy if exists "announcements_admin_manage" on public.announcements;
create policy "announcements_admin_manage" on public.announcements for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "faqs_public_select" on public.faqs;
create policy "faqs_public_select" on public.faqs for select using (is_published = true);

drop policy if exists "faqs_admin_manage" on public.faqs;
create policy "faqs_admin_manage" on public.faqs for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "audit_logs_admin_only" on public.audit_logs;
create policy "audit_logs_admin_only" on public.audit_logs for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "email_logs_admin_only" on public.email_logs;
create policy "email_logs_admin_only" on public.email_logs for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "staff_assignments_admin_only" on public.staff_assignments;
create policy "staff_assignments_admin_only" on public.staff_assignments for all using (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "settings_admin_only" on public.settings;
create policy "settings_admin_only" on public.settings for all using (
  public.has_role(array['admin', 'super_admin'])
) with check (
  public.has_role(array['admin', 'super_admin'])
);

drop policy if exists "storage_resident_objects_select" on storage.objects;
create policy "storage_resident_objects_select" on storage.objects for select using (
  (
    bucket_id in ('resident-documents', 'application-documents', 'ids')
    and (split_part(name, '/', 1) = auth.uid()::text or public.has_role(array['admin', 'super_admin', 'social_worker']))
  )
  or (bucket_id = 'requirements' and auth.role() = 'authenticated')
);

drop policy if exists "storage_resident_objects_insert" on storage.objects;
create policy "storage_resident_objects_insert" on storage.objects for insert with check (
  (
    bucket_id in ('resident-documents', 'application-documents', 'ids')
    and split_part(name, '/', 1) = auth.uid()::text
  )
  or (bucket_id = 'requirements' and public.has_role(array['admin', 'super_admin']))
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "storage_resident_objects_update" on storage.objects;
create policy "storage_resident_objects_update" on storage.objects for update using (
  (
    bucket_id in ('resident-documents', 'application-documents', 'ids')
    and split_part(name, '/', 1) = auth.uid()::text
  )
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
) with check (
  (
    bucket_id in ('resident-documents', 'application-documents', 'ids')
    and split_part(name, '/', 1) = auth.uid()::text
  )
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
);

drop policy if exists "storage_resident_objects_delete" on storage.objects;
create policy "storage_resident_objects_delete" on storage.objects for delete using (
  (
    bucket_id in ('resident-documents', 'application-documents', 'ids')
    and split_part(name, '/', 1) = auth.uid()::text
  )
  or public.has_role(array['admin', 'super_admin', 'social_worker'])
);
